buildProtEnrichResultsDownloadFilename <- function(selectedContrast,
                                                   date = Sys.Date(),
                                                   prefix = "Enrichment_results") {
  contrastSafe <- gsub("[^A-Za-z0-9_.-]", "_", selectedContrast)
  paste0(prefix, "_", contrastSafe, "_", date, ".zip")
}

writeProtEnrichResultsDownloadArchive <- function(file,
                                                  selectedContrast,
                                                  methodInfo,
                                                  organismTaxid,
                                                  upCutoff,
                                                  downCutoff,
                                                  qCutoff,
                                                  gprofilerResults = NULL,
                                                  clusterprofilerResults = NULL,
                                                  stringdbResults = NULL,
                                                  tempDir = tempdir(),
                                                  writeTsvFn = readr::write_tsv,
                                                  writeLinesFn = writeLines,
                                                  zipFn = utils::zip,
                                                  sysTimeFn = Sys.time) {
  tryCatch({
    filesToZip <- character()

    if (!is.null(gprofilerResults) && nrow(gprofilerResults) > 0) {
      gprofilerFile <- file.path(tempDir, "gprofiler2_results.tsv")
      writeTsvFn(gprofilerResults, gprofilerFile)
      filesToZip <- c(filesToZip, gprofilerFile)
    }

    if (!is.null(clusterprofilerResults) && nrow(clusterprofilerResults) > 0) {
      clusterprofilerFile <- file.path(tempDir, "clusterProfileR_results.tsv")
      writeTsvFn(clusterprofilerResults, clusterprofilerFile)
      filesToZip <- c(filesToZip, clusterprofilerFile)
    }

    if (!is.null(stringdbResults) && nrow(stringdbResults) > 0) {
      stringdbFile <- file.path(tempDir, "stringdb_results.tsv")
      writeTsvFn(stringdbResults, stringdbFile)
      filesToZip <- c(filesToZip, stringdbFile)
    }

    summaryFile <- file.path(tempDir, "enrichment_analysis_summary.txt")
    summaryContent <- paste(
      "# MultiScholaR Enrichment Analysis Results",
      paste("Date:", sysTimeFn()),
      paste("Contrast:", selectedContrast),
      paste("Analysis Method:", methodInfo$method),
      paste("Organism:", methodInfo$species_name),
      paste("Taxonomy ID:", organismTaxid),
      "",
      "## Analysis Parameters:",
      paste("Up log2FC Cutoff:", upCutoff),
      paste("Down log2FC Cutoff:", downCutoff),
      paste("Q-value Cutoff:", qCutoff),
      "",
      "## Results Summary:",
      paste("gprofiler2 terms:", if (!is.null(gprofilerResults)) nrow(gprofilerResults) else 0),
      paste("clusterProfileR terms:", if (!is.null(clusterprofilerResults)) nrow(clusterprofilerResults) else 0),
      paste("STRING-DB networks:", if (!is.null(stringdbResults)) nrow(stringdbResults) else 0),
      "",
      "## Files Included:",
      if (length(filesToZip) > 0) paste("*", basename(filesToZip), collapse = "\n") else "* No result files (analysis may have failed)",
      "",
      "Generated by MultiScholaR Enrichment Analysis Module",
      sep = "\n"
    )

    writeLinesFn(summaryContent, summaryFile)
    filesToZip <- c(filesToZip, summaryFile)

    if (length(filesToZip) > 0) {
      zipFn(zipfile = file, files = filesToZip, flags = "-j")
    } else {
      noteFile <- file.path(tempDir, "no_results.txt")
      writeLinesFn("No enrichment results available to download.", noteFile)
      zipFn(zipfile = file, files = noteFile, flags = "-j")
      filesToZip <- noteFile
    }

    invisible(list(
      status = "ok",
      files = filesToZip,
      zipfile = file
    ))
  }, error = function(e) {
    errorFile <- file.path(tempDir, "download_error.txt")
    writeLinesFn(paste("Error creating download:", e$message), errorFile)
    zipFn(zipfile = file, files = errorFile, flags = "-j")

    invisible(list(
      status = "error",
      files = errorFile,
      zipfile = file,
      error = e$message
    ))
  })
}

