name: 🐛 Bug Report (Parent)
description: Report a major bug that requires multiple fixes or investigations
title: "[BUG] "
labels: ["bug", "parent"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! This template is for major bugs that require multiple sub-tasks to resolve.
        
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug's impact on users?
      options:
        - Critical (System/Data Loss)
        - High (Feature Unusable)
        - Medium (Feature Degraded)
        - Low (Minor Issue)
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug to fix?
      options:
        - P0 (Fix Immediately)
        - P1 (Fix This Sprint)
        - P2 (Fix Next Sprint)
        - P3 (Fix When Possible)
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: "Example: Data processing fails when handling large datasets"
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce this behavior
      placeholder: |
        1. Load dataset '...'
        2. Run function '...'
        3. See error
    validations:
      required: false
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen when following these steps?
      placeholder: "The function should process the dataset and return results"
    validations:
      required: false
      
  - type: textarea
    id: current-workaround
    attributes:
      label: Current Workaround
      description: Is there any temporary workaround for this issue?
      placeholder: "Example: Splitting large datasets into smaller chunks works as a temporary solution"
    validations:
      required: false
      
  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: List the main components or areas affected by this bug
      placeholder: |
        1. Data processing module
        2. File handling system
        3. Output generation
    validations:
      required: false
      
  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Provide details about your environment
      placeholder: |
        - OS: [e.g., Windows 10]
        - R Version: [e.g., 4.1.0]
        - Package Version: [e.g., 1.0.0]
        - Relevant Package Versions: [e.g., tidyverse 1.3.0]
    validations:
      required: false
      
  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the impact of this bug on users and systems?
      placeholder: |
        - Number of users affected
        - Data integrity implications
        - Performance impact
        - Security implications
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the bug here
    validations:
      required: false