name: 🔧 Bug Fix Task (Child)
description: Create a specific bug fix task that is part of a larger bug report
title: "[FIX] "
labels: ["bug-fix", "child"]
body:
  - type: markdown
    attributes:
      value: |
        This template is for creating specific fix tasks that are part of a larger bug report.
        
  - type: input
    id: parent-issue
    attributes:
      label: Parent Bug Report
      description: Link to the parent bug report issue
      placeholder: "#123"
    validations:
      required: true
      
  - type: dropdown
    id: estimated-effort
    attributes:
      label: Estimated Effort
      description: How much effort is required for this fix?
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (4-8 hours)
        - L (1-2 days)
        - XL (2+ days)
    validations:
      required: true
      
  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: What is the risk level of implementing this fix?
      options:
        - High (Major System Changes)
        - Medium (Moderate Changes)
        - Low (Isolated Changes)
        - Minimal (Simple Fix)
    validations:
      required: true
      
  - type: textarea
    id: fix-description
    attributes:
      label: Fix Description
      description: Describe the specific fix or investigation needed
      placeholder: "Example: Fix memory leak in data processing loop"
    validations:
      required: true
      
  - type: textarea
    id: implementation-plan
    attributes:
      label: Implementation Plan
      description: Outline the approach for implementing this fix
      placeholder: |
        1. Identify the source of the memory leak
        2. Implement proper memory management
        3. Add cleanup routines
    validations:
      required: true
      
  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How will this fix be tested?
      placeholder: |
        Unit Tests:
        - [ ] Test case for memory management
        - [ ] Test edge cases
        
        Integration Tests:
        - [ ] Test with large datasets
        - [ ] Test with concurrent operations
        
        Performance Tests:
        - [ ] Memory profiling
        - [ ] Performance benchmarking
        
        Regression Tests:
        - [ ] Verify no impact on related functionality
    validations:
      required: true
      
  - type: textarea
    id: potential-impacts
    attributes:
      label: Potential Impacts
      description: What other parts of the system might be affected by this fix?
      placeholder: |
        Dependencies:
        - List affected modules
        - List affected functions
        
        Performance:
        - Expected impact on memory usage
        - Expected impact on processing speed
        
        Configuration:
        - Required setting changes
        - Migration steps needed
    validations:
      required: true
      
  - type: textarea
    id: rollback-plan
    attributes:
      label: Rollback Plan
      description: How can this change be rolled back if needed?
      placeholder: |
        1. Steps to revert changes
        2. Data recovery process if needed
        3. Communication plan
    validations:
      required: true