blank_issues_enabled: false
contact_links:
  - name: ProteomeScholaR Documentation
    url: https://github.com/APAF-bioinformatics/ProteomeScholaR/wiki
    about: Check our documentation for guides and troubleshooting