name: 📚 Documentation Project (Parent)
description: Create a new documentation project that requires multiple tasks
title: "[DOCS] "
labels: ["documentation", "parent"]
body:
  - type: markdown
    attributes:
      value: |
        This template is for major documentation projects that require multiple sub-tasks.
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this?
      options:
        - User Guide
        - API Reference
        - Technical Documentation
        - Tutorial/Workshop
        - Installation Guide
        - Contributing Guide
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this documentation needed?
      options:
        - P0 (Blocking Release)
        - P1 (Required This Sprint)
        - P2 (Required Next Sprint)
        - P3 (Nice to Have)
    validations:
      required: true
      
  - type: textarea
    id: documentation-scope
    value:
      label: Documentation Scope
      description: What area of the project needs documentation?
      placeholder: "Example: Complete user guide for data analysis workflow"
    validations:
      required: true
      
  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience
      description: Who is this documentation for? Be specific about expertise levels.
      placeholder: |
        Primary Audience:
        - Role: [e.g., Data Scientists]
        - Technical Level: [e.g., Intermediate R users]
        
        Secondary Audience:
        - Role: [e.g., Bioinformaticians]
        - Technical Level: [e.g., Advanced]
        
        Prerequisites:
        - Required knowledge
        - Required tools/software
    validations:
      required: false
      
  - type: textarea
    id: required-sections
    attributes:
      label: Required Sections
      description: List the main sections or components that need documentation
      placeholder: |
        1. Overview
           - Purpose
           - Key concepts
        2. Getting Started
           - Installation
           - Configuration
        3. Main Content
           - Core functionality
           - Examples
        4. Advanced Topics
           - Best practices
           - Troubleshooting
    validations:
      required: false
      
  - type: textarea
    id: resources-needed
    attributes:
      label: Resources Needed
      description: What resources are needed for this documentation?
      placeholder: |
        Code Examples:
        - List specific functionalities needing examples
        - Test datasets required
        
        Visual Assets:
        - Diagrams needed
        - Screenshots required
        - Video tutorials planned
        
        External Resources:
        - API documentation links
        - Reference papers
    validations:
      required: false
      
  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Technical aspects that need to be documented
      placeholder: |
        API Documentation:
        - Functions to document
        - Parameters to explain
        
        Code Examples:
        - Use cases to cover
        - Edge cases to address
        
        Performance Considerations:
        - Memory requirements
        - Processing time expectations
    validations:
      required: false
      
  - type: textarea
    id: accessibility-requirements
    attributes:
      label: Accessibility Requirements
      description: How will we ensure the documentation is accessible?
      placeholder: |
        - Alt text for images
        - Screen reader compatibility
        - Color contrast requirements
        - Multiple format availability (PDF, HTML, etc.)
    validations:
      required: false
      
  - type: textarea
    id: version-tracking
    attributes:
      label: Version Information
      description: Version details for this documentation
      placeholder: |
        Documentation Version: [e.g., 1.0.0]
        Applies to Software Versions:
        - Package version range
        - Dependency version requirements
        
        Change Management:
        - How will updates be tracked?
        - Where will changelog be maintained?
    validations:
      required: false
      
  - type: textarea
    id: completion-criteria
    attributes:
      label: Completion Criteria
      description: What criteria must be met for this documentation to be complete?
      placeholder: |
        Content Requirements:
        - [ ] All sections written
        - [ ] Code examples tested
        - [ ] Screenshots current
        
        Review Requirements:
        - [ ] Technical review by dev team
        - [ ] User testing feedback
        - [ ] Accessibility review
        
        Publishing Requirements:
        - [ ] Formatted for all platforms
        - [ ] Indexed for search
        - [ ] Integrated with existing docs
    validations:
      required: false