name: 🚀 Feature Request (Parent)
description: Create a new feature request that will serve as a parent task
title: "[FEATURE] "
labels: ["enhancement", "parent"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new feature! This template is for major feature requests that will have multiple sub-tasks.
        
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you'd like to see implemented
      placeholder: "Example: Add support for processing multiple datasets in parallel"
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problems will it solve?
      placeholder: "Example: This feature will improve processing speed and allow batch analysis of multiple experiments"
    validations:
      required: true
      
  - type: textarea
    id: expected-components
    attributes:
      label: Expected Components/Sub-tasks
      description: List the main components or sub-tasks that you expect will be needed to implement this feature
      placeholder: |
        1. Component/Function A
        2. Component/Function B
        3. Integration with existing system
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Documentation updated
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here
    validations:
      required: false 