# ----------------------------------------------------------------------------
# printPValuesDistribution
# ----------------------------------------------------------------------------
#' Draw the p-values distribution plot.
#' @param selected_data A table that is generated by running the function \code{\link{get_significant_data}}.
#' @param log_p_value_column The name of the column representing the p-value.
#' @param formula_string The formula string used in the facet_grid command for the ggplot scatter plot.
#' @export
printPValuesDistribution <- function(selected_data, p_value_column = raw_pvalue, formula_string = "is_ruv_applied ~ comparison") {
  breaks <- c(
    0, 0.001, 0.01, 0.05,
    seq(0.1, 1, by = 0.1)
  )

  # after_stat(density)
  pvalhist <- ggplot(selected_data, aes({{ p_value_column }})) +
    theme(axis.title.y = element_blank()) +
    xlab("P-value") +
    geom_histogram(aes(y = after_stat(density)),
      breaks = breaks,
      position = "identity",
      color = "black"
    ) +
    geom_histogram(aes(y = after_stat(density)),
      breaks = breaks,
      position = "identity"
    )

  if (!is.na(formula_string)) {
    pvalhist <- pvalhist +
      facet_grid(as.formula(formula_string))
  }


  pvalhist
}

# ----------------------------------------------------------------------------
# gg_save_logging
# ----------------------------------------------------------------------------
#' @export
gg_save_logging <- function(
  input_plot,
  file_name_part,
  plots_format,
  width = 7,
  height = 7
) {
  for (format_ext in plots_format) {
    file_name <- paste0(file_name_part, format_ext)
    captured_output <- capture.output(
      ggsave(
        plot = input_plot,
        filename = file_name,
        width = width,
        height = height
      ),
      type = "message"
    )
    logdebug(captured_output)
  }
}

# ----------------------------------------------------------------------------
# summarizeQCPlot
# ----------------------------------------------------------------------------
#' @export
summarizeQCPlot <- function(qc_figure) {
  cat("RLE Plots:\n")
  for (plot_name in names(qc_figure@rle_plots)) {
    cat(paste(" -", plot_name, "\n"))
    print(qc_figure@rle_plots[[plot_name]])
  }

  cat("\nPCA Plots:\n")
  for (plot_name in names(qc_figure@pca_plots)) {
    cat(paste(" -", plot_name, "\n"))
    print(qc_figure@pca_plots[[plot_name]])
  }

  cat("\nDensity Plots:\n")
  for (plot_name in names(qc_figure@density_plots)) {
    cat(paste(" -", plot_name, "\n"))
    print(qc_figure@density_plots[[plot_name]])
  }

  cat("\nPearson Correlation Plots:\n")
  for (plot_name in names(qc_figure@pearson_plots)) {
    cat(paste(" -", plot_name, "\n"))
    print(qc_figure@pearson_plots[[plot_name]])
  }
}

# ----------------------------------------------------------------------------
# plotPcaDispatch (renamed from plotPca to avoid S4 generic conflict)
# ----------------------------------------------------------------------------
plotPcaDispatch <- function(theObject, grouping_variable, shape_variable = NULL, label_column, title, font_size = 8, cv_percentile = 0.90) {
  # Defensive checks
  if (!is.character(grouping_variable) || length(grouping_variable) != 1) {
    stop("grouping_variable must be a single character string")
  }

  if (!is.null(shape_variable) && (!is.character(shape_variable) || length(shape_variable) != 1)) {
    stop("shape_variable must be NULL or a single character string")
  }

  if (!grouping_variable %in% colnames(theObject@design_matrix)) {
    stop(sprintf("grouping_variable '%s' not found in design matrix", grouping_variable))
  }

  if (!is.null(shape_variable) && !shape_variable %in% colnames(theObject@design_matrix)) {
    stop(sprintf("shape_variable '%s' not found in design matrix", shape_variable))
  }

  data_matrix <- NULL
  ## I want to check the class of theObject here
  if (class(theObject) == "PeptideQuantitativeData") {
    data_matrix <- theObject@peptide_matrix
  } else if (class(theObject) == "ProteinQuantitativeData") {
    data_matrix <- theObject@protein_quant_table |>
      column_to_rownames(var = "Protein.Ids") |>
      as.matrix()
  }

  design_matrix <- theObject@design_matrix
  sample_id <- theObject@sample_id

  # Prepare matrix for PCA (data should already be log2 transformed)
  data_matrix_pca <- data_matrix
  data_matrix_pca[!is.finite(data_matrix_pca)] <- NA

  if (is.na(label_column) || label_column == "") {
    label_column <- ""
  }

  pca_plot <- plotPcaHelper(data_matrix_pca,
    design_matrix = design_matrix,
    sample_id_column = sample_id,
    grouping_variable = grouping_variable,
    shape_variable = shape_variable,
    label_column = label_column,
    title = title,
    geom.text.size = font_size,
    cv_percentile = cv_percentile
  )

  return(pca_plot)
}

