# ----------------------------------------------------------------------------
# findBestK
# ----------------------------------------------------------------------------
## -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#'@export
findBestK <- function( cancorplot_r1) {
  message("--- DEBUG66: Entering findBestK ---")
  controls_idx <- which(cancorplot_r1$data$featureset == "Control")
  all_idx <- which( cancorplot_r1$data$featureset == "All")
  difference_between_all_ctrl <- cancorplot_r1$data$cc[all_idx] - cancorplot_r1$data$cc[controls_idx]
  max_difference <- max(difference_between_all_ctrl, na.rm=TRUE)
  message(sprintf("   DEBUG66: max_difference = %.4f", max_difference))
  best_idx <- which( difference_between_all_ctrl == max_difference)
  best_k <- (cancorplot_r1$data$K[controls_idx] )[best_idx]
  message(sprintf("   DEBUG66: best_k (internal) = %s", as.character(best_k)))
  return( best_k)
}

# ----------------------------------------------------------------------------
# findBestKForAssayList
# ----------------------------------------------------------------------------
#' Find the Best K Value for RUV from a List of Canonical Correlation Plots
#'
#' This function iterates over a list of canonical correlation plots (typically
#' generated by `ruvCancor` for multi-assay objects like `MetaboliteAssayData`)
#' and applies the `findBestK` logic to each plot to determine the optimal
#' number of unwanted variation factors (k) for each assay.
#'
#' @param cancor_plots_list A named list where each element is a ggplot object
#'   returned by `ruv_cancorplot` (the output of `ruvCancor` for a multi-assay
#'   object).
#'
#' @return A named list where keys are the assay names (from the input list)
#'   and values are the determined best K for each assay. Returns `NA_integer_`
#'   for assays where `findBestK` fails or returns an invalid result.
#'
#' @importFrom purrr map set_names
#' @importFrom logger log_warn
#' @export
findBestKForAssayList <- function(cancor_plots_list) {

    # --- Input Validation ---
    if (!is.list(cancor_plots_list)) {
        stop("`cancor_plots_list` must be a list.")
    }
    if (length(cancor_plots_list) == 0) {
        log_warn("`cancor_plots_list` is empty. Returning an empty list.")
        return(list())
    }
    if (is.null(names(cancor_plots_list)) || any(names(cancor_plots_list) == "")) {
        log_warn("Input list is not fully named. Assigning default names (Plot_1, Plot_2, ...)")
        names(cancor_plots_list) <- paste0("Plot_", seq_along(cancor_plots_list))
    }

    # --- Iterate and Apply findBestK ---
    best_k_list <- purrr::map(seq_along(cancor_plots_list), function(i) {
        assay_name <- names(cancor_plots_list)[i]
        current_plot <- cancor_plots_list[[i]]

        # Check if it's a ggplot object
        if (!inherits(current_plot, "ggplot")) {
            log_warn("Element '{assay_name}' in the list is not a ggplot object. Skipping.", .logr = TRUE)
            return(NA_integer_)
        }

        # Call the original findBestK function
        best_k_assay <- tryCatch({
            k <- findBestK(current_plot)
            # Add a check for Inf or non-numeric result which might cause issues later
            if (is.infinite(k) || !is.numeric(k) || length(k) != 1) {
                 log_warn("Assay '{assay_name}': findBestK returned an invalid value ({k}). Returning NA.", .logr = TRUE)
                 NA_integer_
            } else {
                 # Ensure it's an integer
                 as.integer(k)
            }
        }, warning = function(w) {
            # Catch the specific warning from findBestK if max returns -Inf
            if (grepl("no non-missing arguments to max", w$message, ignore.case = TRUE)) {
                log_warn("Assay '{assay_name}': Warning in findBestK (likely no valid data in plot): {w$message}. Returning NA.", .logr = TRUE)
            } else {
                # Log other warnings but still try to return NA
                log_warn("Assay '{assay_name}': Warning during findBestK: {w$message}. Returning NA.", .logr = TRUE)
            }
            NA_integer_
        }, error = function(e) {
            log_warn("Assay '{assay_name}': Error calling findBestK: {e$message}. Returning NA.", .logr = TRUE)
            NA_integer_
        })

        return(best_k_assay)
    })

    # Set names for the result list
    names(best_k_list) <- names(cancor_plots_list)

    return(best_k_list)
}

# ----------------------------------------------------------------------------
# calculateSeparationScore
# ----------------------------------------------------------------------------
#' Calculate Separation Score for Canonical Correlation Plot
#'
#' Internal helper function to calculate separation quality between "All" and "Control"
#' groups in a canonical correlation plot.
#'
#' @param cancorplot A ggplot object from ruvCancor
#' @param metric The separation metric to calculate
#'
#' @return A numeric separation score (higher is better)
#'
#' @keywords internal
calculateSeparationScore <- function(cancorplot, metric = "max_difference") {
  message(sprintf("--- DEBUG66: Entering calculateSeparationScore (metric=%s) ---", metric))
  
  # Extract data from the plot
  if (!inherits(cancorplot, "ggplot") || is.null(cancorplot$data)) {
    message("   DEBUG66: Invalid cancorplot")
    return(NA_real_)
  }
  
  plot_data <- cancorplot$data
  
  # Check required columns exist
  if (!all(c("featureset", "cc", "K") %in% colnames(plot_data))) {
    message("   DEBUG66: Missing columns in plot_data")
    return(NA_real_)
  }
  
  # Get indices for Control and All groups
  controls_idx <- which(plot_data$featureset == "Control")
  all_idx <- which(plot_data$featureset == "All")
  
  if (length(controls_idx) == 0 || length(all_idx) == 0) {
    message("   DEBUG66: No Control or All groups found")
    return(NA_real_)
  }
  
  # Calculate differences between All and Control
  difference_between_all_ctrl <- plot_data$cc[all_idx] - plot_data$cc[controls_idx]
  
  # Remove any NA or infinite values
  valid_diffs <- difference_between_all_ctrl[is.finite(difference_between_all_ctrl)]
  
  if (length(valid_diffs) == 0) {
    return(NA_real_)
  }
  
  # Calculate score based on specified metric
  score <- switch(metric,
    "max_difference" = max(valid_diffs, na.rm = TRUE),
    "mean_difference" = mean(valid_diffs, na.rm = TRUE),
    "auc" = {
      # Area under the curve (trapezoidal rule approximation)
      k_values <- plot_data$K[all_idx][is.finite(difference_between_all_ctrl)]
      if (length(k_values) < 2) return(NA_real_)
      
      # Sort by K value
      sorted_idx <- order(k_values)
      k_sorted <- k_values[sorted_idx]
      diff_sorted <- valid_diffs[sorted_idx]
      
      # Calculate AUC using trapezoidal rule
      sum(diff(k_sorted) * (head(diff_sorted, -1) + tail(diff_sorted, -1)) / 2)
    },
    "weighted_difference" = {
      # Weight differences by their K value (higher K gets more weight)
      k_values <- plot_data$K[all_idx][is.finite(difference_between_all_ctrl)]
      if (length(k_values) == 0) return(NA_real_)
      
      weights <- k_values / max(k_values, na.rm = TRUE)
      sum(valid_diffs * weights, na.rm = TRUE) / sum(weights, na.rm = TRUE)
    },
    NA_real_
  )
  
  message(sprintf("   DEBUG66: Calculated score = %.4f", score))
  return(as.numeric(score))
}

# ----------------------------------------------------------------------------
# calculateCompositeScore
# ----------------------------------------------------------------------------
#' Calculate Composite Score for Percentage Optimization
#'
#' Internal helper function to calculate a composite score that considers both
#' separation quality and the resulting k value from findBestK(). This prevents
#' over-optimization towards percentages that give good separation but unreasonably
#' high k values that would remove biological signal.
#'
#' @param separation_score The separation score from calculateSeparationScore()
#' @param best_k The best k value from findBestK()
#' @param k_penalty_weight Weight for k penalty (0-1). Higher values penalize high k more
#' @param max_acceptable_k Maximum acceptable k value. k values above this get heavy penalty
#'
#' @return A numeric composite score (higher is better)
#'
#' @keywords internal
calculateCompositeScore <- function(separation_score, best_k, k_penalty_weight, max_acceptable_k) {
  message(sprintf("--- DEBUG66: Entering calculateCompositeScore (sep=%.4f, k=%s) ---", separation_score, as.character(best_k)))
  
  # Handle NA cases
  if (is.na(separation_score) || is.na(best_k)) {
    return(NA_real_)
  }
  
  # Ensure positive values
  if (separation_score <= 0) {
    return(0)
  }
  
  # Calculate k penalty
  if (best_k <= max_acceptable_k) {
    # Linear penalty within acceptable range: penalty = 0 at k=1, penalty = k_penalty_weight at k=max_acceptable_k
    k_penalty <- k_penalty_weight * (best_k - 1) / (max_acceptable_k - 1)
  } else {
    # Heavy penalty for k values above max_acceptable_k
    # Exponential penalty: starts at k_penalty_weight and increases rapidly
    excess_k <- best_k - max_acceptable_k
    k_penalty <- k_penalty_weight + (1 - k_penalty_weight) * (1 - exp(-excess_k))
  }
  
  # Ensure k_penalty is between 0 and 1
  k_penalty <- pmax(0, pmin(1, k_penalty))
  message(sprintf("   DEBUG66: k_penalty = %.4f", k_penalty))
  
  # Calculate composite score: separation_score * (1 - k_penalty)
  # This means:
  # - k=1: no penalty (multiply by 1)
  # - k=max_acceptable_k: penalty = k_penalty_weight (multiply by 1-k_penalty_weight)
  # - k>max_acceptable_k: heavy penalty (multiply by value approaching 0)
  composite_score <- separation_score * (1 - k_penalty)
  message(sprintf("   DEBUG66: composite_score = %.4f", composite_score))
  
  return(as.numeric(composite_score))
}

# ----------------------------------------------------------------------------
# calculateAdaptiveMaxK
# ----------------------------------------------------------------------------
#' Calculate Adaptive Maximum Acceptable K Based on Sample Size
#'
#' Internal helper function to determine an appropriate max_acceptable_k value
#' based on the number of samples in the dataset. This prevents over-correction
#' in small datasets and allows more flexibility in large datasets.
#'
#' @param sample_size Number of samples in the dataset
#'
#' @return An integer representing the adaptive max_acceptable_k value
#'
#' @details
#' The adaptive calculation follows these principles:
#' - Small datasets (n < 15): Conservative approach, max_k = 2
#' - Medium datasets (n = 15-40): Standard approach, max_k = 3  
#' - Large datasets (n = 40-80): Moderate approach, max_k = 4
#' - Very large datasets (n > 80): Permissive approach, max_k = 5
#' 
#' The rationale is that with more samples, you have more degrees of freedom
#' and statistical power, making higher k values less problematic.
#'
#' @keywords internal
calculateAdaptiveMaxK <- function(sample_size) {
  
  if (sample_size < 15) {
    # Small datasets: be very conservative
    # Each k factor consumes significant degrees of freedom
    return(2L)
  } else if (sample_size < 40) {
    # Medium datasets: standard approach
    # This is the typical proteomics experiment size
    return(3L)
  } else if (sample_size < 80) {
    # Large datasets: can afford one extra k factor
    # Sufficient statistical power to handle k=4
    return(4L)
  } else {
    # Very large datasets: most permissive
    # Abundant statistical power allows k=5 if separation justifies it
    return(5L)
  }
}

