# ----------------------------------------------------------------------------
# .extractCancorCurveData
# ----------------------------------------------------------------------------
#' @keywords internal
.extractCancorCurveData <- function(cancorplot) {
  plot_data <- if (inherits(cancorplot, "ggplot")) {
    cancorplot$data
  } else if (is.list(cancorplot) && !is.null(cancorplot$data)) {
    cancorplot$data
  } else {
    return(NULL)
  }

  required_cols <- c("featureset", "K", "cc")
  if (is.null(plot_data) || !all(required_cols %in% colnames(plot_data))) {
    return(NULL)
  }

  dup_check <- plot_data |>
    dplyr::group_by(featureset, K) |>
    dplyr::summarise(n = dplyr::n(), .groups = "drop") |>
    dplyr::filter(n > 1)
  if (nrow(dup_check) > 0) {
    return(NULL)
  }

  curve <- plot_data |>
    dplyr::select(featureset, K, cc) |>
    tidyr::pivot_wider(names_from = featureset, values_from = cc) |>
    dplyr::arrange(K)

  if (!all(c("All", "Control", "K") %in% colnames(curve))) {
    return(NULL)
  }

  curve |>
    dplyr::mutate(delta = All - Control)
}

# ----------------------------------------------------------------------------
# findBestK
# ----------------------------------------------------------------------------
#' @export
findBestK <- function(cancorplot_r1) {
  .Deprecated("findBestKElbow")
  findBestKElbow(cancorplot_r1)
}

# ----------------------------------------------------------------------------
# findBestKElbow
# ----------------------------------------------------------------------------
#' Find Best K Using First-Plateau Detection
#'
#' Selects the smallest K whose All-vs-Control separation is within epsilon of
#' the maximum observed separation. Malformed inputs return NA. Valid weak-effect
#' curves return 1L.
#'
#' @param cancorplot A ggplot object or list with `$data`.
#' @param epsilon Numeric tolerance below the maximum delta. Default 0.05.
#' @param min_effect Minimum meaningful max(delta). Default 0.05.
#'
#' @return A scalar integer K, or NA_integer_ for invalid input.
#' @export
findBestKElbow <- function(cancorplot, epsilon = 0.05, min_effect = 0.05) {
  curve <- .extractCancorCurveData(cancorplot)
  if (is.null(curve)) {
    return(NA_integer_)
  }

  valid_rows <- curve[is.finite(curve$delta) & is.finite(curve$K), , drop = FALSE]
  if (nrow(valid_rows) == 0) {
    return(NA_integer_)
  }

  max_delta <- max(valid_rows$delta, na.rm = TRUE)
  if (!is.finite(max_delta)) {
    return(NA_integer_)
  }

  if (max_delta < min_effect) {
    return(1L)
  }

  target <- max_delta * (1 - epsilon)
  candidates <- valid_rows$K[valid_rows$delta >= target]
  if (length(candidates) == 0) {
    return(NA_integer_)
  }

  as.integer(min(candidates))
}

# ----------------------------------------------------------------------------
# findBestKForAssayList
# ----------------------------------------------------------------------------
#' Find the Best K Value for RUV from a List of Canonical Correlation Plots
#'
#' This function iterates over a list of canonical correlation plots (typically
#' generated by `ruvCancor` for multi-assay objects like `MetaboliteAssayData`)
#' and applies the `findBestK` logic to each plot to determine the optimal
#' number of unwanted variation factors (k) for each assay.
#'
#' @param cancor_plots_list A named list where each element is a ggplot object
#'   returned by `ruv_cancorplot` (the output of `ruvCancor` for a multi-assay
#'   object).
#'
#' @return A named list where keys are the assay names (from the input list)
#'   and values are the determined best K for each assay. Returns `NA_integer_`
#'   for assays where `findBestK` fails or returns an invalid result.
#'
#' @importFrom purrr map set_names
#' @importFrom logger log_warn
#' @export
findBestKForAssayList <- function(cancor_plots_list) {

    # --- Input Validation ---
    if (!is.list(cancor_plots_list)) {
        stop("`cancor_plots_list` must be a list.")
    }
    if (length(cancor_plots_list) == 0) {
        log_warn("`cancor_plots_list` is empty. Returning an empty list.")
        return(list())
    }
    if (is.null(names(cancor_plots_list)) || any(names(cancor_plots_list) == "")) {
        log_warn("Input list is not fully named. Assigning default names (Plot_1, Plot_2, ...)")
        names(cancor_plots_list) <- paste0("Plot_", seq_along(cancor_plots_list))
    }

    # --- Iterate and Apply findBestK ---
    best_k_list <- purrr::map(seq_along(cancor_plots_list), function(i) {
        assay_name <- names(cancor_plots_list)[i]
        current_plot <- cancor_plots_list[[i]]

        # Check if it's a ggplot object
        if (!inherits(current_plot, "ggplot")) {
            log_warn("Element '{assay_name}' in the list is not a ggplot object. Skipping.", .logr = TRUE)
            return(NA_integer_)
        }

            best_k_assay <- tryCatch({
            findBestKElbow(current_plot)
        }, error = function(e) {
            log_warn(paste("Assay", assay_name, ": Error calling findBestKElbow:", e$message, ". Returning NA."))
            NA_integer_
        })

        return(best_k_assay)
    })

    # Set names for the result list
    names(best_k_list) <- names(cancor_plots_list)

    return(best_k_list)
}

# ----------------------------------------------------------------------------
# calculateSeparationScore
# ----------------------------------------------------------------------------
#' Calculate Separation Score for Canonical Correlation Plot
#'
#' Internal helper function to calculate separation quality between "All" and "Control"
#' groups in a canonical correlation plot.
#'
#' @param cancorplot A ggplot object from ruvCancor
#' @param metric The separation metric to calculate
#'
#' @return A numeric separation score (higher is better)
#'
#' @keywords internal
calculateSeparationScore <- function(cancorplot, metric = "max_difference") {
  curve <- .extractCancorCurveData(cancorplot)
  if (is.null(curve)) {
    return(NA_real_)
  }

  valid_rows <- curve[is.finite(curve$delta), , drop = FALSE]
  if (nrow(valid_rows) == 0) {
    return(NA_real_)
  }

  score <- switch(metric,
    "max_difference" = max(valid_rows$delta),
    "mean_difference" = mean(valid_rows$delta),
    "auc" = {
      if (nrow(valid_rows) < 2) return(NA_real_)
      sorted <- valid_rows[order(valid_rows$K), ]
      sum(diff(sorted$K) * (head(sorted$delta, -1) + tail(sorted$delta, -1)) / 2)
    },
    "weighted_difference" = {
      weights <- valid_rows$K / max(valid_rows$K)
      sum(valid_rows$delta * weights) / sum(weights)
    },
    NA_real_
  )

  as.numeric(score)
}

# ----------------------------------------------------------------------------
# calculateCompositeScore
# ----------------------------------------------------------------------------
#' Calculate Composite Score for Percentage Optimization
#'
#' Internal helper function to calculate a composite score that considers both
#' separation quality and the resulting k value from findBestK(). This prevents
#' over-optimization towards percentages that give good separation but unreasonably
#' high k values that would remove biological signal.
#'
#' @param separation_score The separation score from calculateSeparationScore()
#' @param best_k The best k value from findBestK()
#' @param k_penalty_weight Weight for k penalty (0-1). Higher values penalize high k more
#' @param max_acceptable_k Maximum acceptable k value. k values above this get heavy penalty
#'
#' @return A numeric composite score (higher is better)
#'
#' @keywords internal
calculateCompositeScore <- function(separation_score, best_k, k_penalty_weight, max_acceptable_k) {
  if (!is.finite(separation_score) || !is.finite(best_k)) {
    return(NA_real_)
  }

  if (!is.finite(max_acceptable_k) || max_acceptable_k < 1) {
    return(NA_real_)
  }

  if (separation_score <= 0) {
    return(0)
  }

  if (max_acceptable_k == 1) {
    k_penalty <- if (best_k <= 1) 0 else 1
  } else if (best_k <= max_acceptable_k) {
    k_penalty <- k_penalty_weight * (best_k - 1) / (max_acceptable_k - 1)
  } else {
    excess_k <- best_k - max_acceptable_k
    k_penalty <- k_penalty_weight + (1 - k_penalty_weight) * (1 - exp(-excess_k))
  }

  k_penalty <- pmax(0, pmin(1, k_penalty))

  as.numeric(separation_score * (1 - k_penalty))
}

# ----------------------------------------------------------------------------
# calculateAdaptiveMaxK
# ----------------------------------------------------------------------------
#' Calculate Adaptive Maximum Acceptable K Based on Sample Size
#'
#' Internal helper function to determine an appropriate max_acceptable_k value
#' based on the number of samples in the dataset. This prevents over-correction
#' in small datasets and allows more flexibility in large datasets.
#'
#' @param sample_size Number of samples in the dataset
#'
#' @return An integer representing the adaptive max_acceptable_k value
#'
#' @details
#' The adaptive calculation follows these principles:
#' - Small datasets (n < 15): Conservative approach, max_k = 2
#' - Medium datasets (n = 15-40): Standard approach, max_k = 3  
#' - Large datasets (n = 40-80): Moderate approach, max_k = 4
#' - Very large datasets (n > 80): Permissive approach, max_k = 5
#' 
#' The rationale is that with more samples, you have more degrees of freedom
#' and statistical power, making higher k values less problematic.
#'
#' @keywords internal
calculateAdaptiveMaxK <- function(sample_size) {
  
  if (sample_size < 15) {
    # Small datasets: be very conservative
    # Each k factor consumes significant degrees of freedom
    return(2L)
  } else if (sample_size < 40) {
    # Medium datasets: standard approach
    # This is the typical proteomics experiment size
    return(3L)
  } else if (sample_size < 80) {
    # Large datasets: can afford one extra k factor
    # Sufficient statistical power to handle k=4
    return(4L)
  } else {
    # Very large datasets: most permissive
    # Abundant statistical power allows k=5 if separation justifies it
    return(5L)
  }
}

# ----------------------------------------------------------------------------
# updateRuvParameters
# ----------------------------------------------------------------------------
##################################################################################################################
#' @export
updateRuvParameters <- function(config_list, best_k, control_genes_index, percentage_as_neg_ctrl) {
  config_list$ruvParameters$best_k <- best_k
  config_list$ruvParameters$num_neg_ctrl <- length(control_genes_index)
  config_list$ruvParameters$percentage_as_neg_ctrl <- percentage_as_neg_ctrl
  
  # Print the number of negative controls (as in the original code)
  config_list$ruvParameters$num_neg_ctrl
  
  # Return the updated config list
  return(config_list)
}

# ----------------------------------------------------------------------------
# getRuvIIIReplicateMatrixHelper
# ----------------------------------------------------------------------------
## -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#'Converts a design matrix to a biological replicate matrix for use with ruvIII.
#'@param design_matrix The design matrix with the sample ID in one column and the experimental group in another column
#'@param sample_id_column The name of the column with the sample ID, tidyverse style input.
#'@param grouping_variable The name of the column with the experimental group, tidyverse style input.
#'@param temp_column The name of the temporary column that indicates which samples are biological replicates of the same experimental group.
#'@return A numeric matrix with rows as samples, columns as experimental group, and a value of 1 for samples within the same experimental group represented by the same column, and a value of zero otherwise.
#'@export
getRuvIIIReplicateMatrixHelper <- function(design_matrix, sample_id_column, grouping_variable, temp_column = is_replicate_temp) {

  ruvIII_replicates_matrix <- design_matrix |>
    dplyr::select({ { sample_id_column } }, { { grouping_variable } }) |>
    mutate({ { temp_column } } := 1) |>
    pivot_wider(id_cols = as_string( as_name(enquo(sample_id_column ))),
                names_from = { { grouping_variable } },
                values_from = { { temp_column } },
                values_fill = 0) |>
    column_to_rownames(as_string(as_name(enquo(sample_id_column)))) |>
    as.matrix()

  ruvIII_replicates_matrix
}

# ----------------------------------------------------------------------------
# getNegCtrlProtAnovaHelper
# ----------------------------------------------------------------------------
#' Identify negative control proteins for use in removal of unwanted variation, using an ANOVA test.
#' @param data_matrix A matrix containing the log (base 2) protein abundance values where each column represents a sample and each row represents a protein group, and proteins as rows. The row ID are the protein accessions. The data is preferably median-scaled with missing values imputed.
#' @param design_matrix A data frame with the design matrix. Matches sample IDs to group IDs.
#' @param grouping_variable The name of the column with the experimental group, as a string.
#' @param num_neg_ctrl The number of negative control genes to select. Typically the number of genes with the highest q-value (e.g. least statistically significant). Default is 100
#' @param ruv_qval_cutoff The FDR threshold. No proteins with q-values lower than this value are included in the list of negative control proteins. This means the number of negative control proteins could be less than the number specified in \code{num_neg_ctrl} when some were excluded by this threshold.
#' @param ruv_fdr_method The FDR calculation method, default is "qvalue". The other option is "BH"
#' @param exclude_pool_samples Logical. If TRUE (default), automatically exclude samples from groups containing "Pool" in their name from ANOVA calculation. Pool/QC samples are excluded from negative control selection but remain in RUV-III correction.
#' @return A boolean vector which indicates which row in the input data matrix is a control gene. The row is included if the value is TRUE. The names of each element is the row ID / protein accessions of the input data matrix.
#'@export
getNegCtrlProtAnovaHelper <- function(data_matrix
                                , design_matrix
                                , grouping_variable = "group"
                                , percentage_as_neg_ctrl = 10
                                , num_neg_ctrl = round( nrow(data_matrix)*percentage_as_neg_ctrl/100, 0)
                                , ruv_qval_cutoff = 0.05
                                , ruv_fdr_method = "qvalue"
                                , exclude_pool_samples = TRUE) {

  message("--- DEBUG66: Entering getNegCtrlProtAnovaHelper ---")
  message(sprintf("   DEBUG66 Arg: grouping_variable = %s", grouping_variable))
  message(sprintf("   DEBUG66 Arg: percentage_as_neg_ctrl = %s", ifelse(is.null(percentage_as_neg_ctrl), "NULL", percentage_as_neg_ctrl)))
  message(sprintf("   DEBUG66 Arg: num_neg_ctrl = %s", ifelse(is.null(num_neg_ctrl), "NULL", num_neg_ctrl)))
  message(sprintf("   DEBUG66 Arg: exclude_pool_samples = %s", exclude_pool_samples))
  message(sprintf("   DEBUG66 Data State: data_matrix dims = %d x %d", nrow(data_matrix), ncol(data_matrix)))
  message(sprintf("   DEBUG66 Data State: design_matrix dims = %d x %d", nrow(design_matrix), ncol(design_matrix)))

  ## Both percentage_as_neg_ctrl and num_neg_ctrl is missing, and number of proteins >= 50 use only 10 percent of the proteins as negative control by default
  if((is.null(percentage_as_neg_ctrl) ||
     is.na(percentage_as_neg_ctrl) ) &&
     (is.null(num_neg_ctrl) ||
      is.na(num_neg_ctrl) ) &&
     nrow(data_matrix) >= 50 ) {
    num_neg_ctrl <- round( nrow(data_matrix)*10/100, 0)
    warnings( paste0( getFunctionName(), ": Using 10% of proteins from the input matrix as negative controls by default.\n"))
    message("   DEBUG66: Defaulting to 10% negative controls")
  } else if (!is.null(percentage_as_neg_ctrl) &
             !is.na(percentage_as_neg_ctrl)) {
    num_neg_ctrl <- round( nrow(data_matrix)*percentage_as_neg_ctrl/100, 0)
  } else if(!is.null(num_neg_ctrl) &
       !is.na(num_neg_ctrl)) {
    num_neg_ctrl <- as.integer(num_neg_ctrl)
  } else {
    stop(paste0( getFunctionName(), ": Please provide either percentage_as_neg_ctrl or num_neg_ctrl.\n"))
  }
  
  message(sprintf("   DEBUG66: Target num_neg_ctrl = %d", num_neg_ctrl))

  # --- Pool/QC Sample Handling ---
  # Pool/QC samples should not influence negative control selection but can help
  # estimate unwanted variation patterns in RUV-III correction
  data_matrix_for_anova <- data_matrix
  design_matrix_for_anova <- design_matrix
  
  if (exclude_pool_samples) {
    message("   DEBUG66: Checking for Pool/QC samples to exclude...")
    # Detect Pool/QC groups (case-insensitive detection)
    all_groups <- unique(design_matrix[[grouping_variable]])
    is_pool_group <- grepl("pool", all_groups, ignore.case = TRUE)
    pool_group_names <- all_groups[is_pool_group]
    
    if (length(pool_group_names) > 0) {
      message(sprintf("   DEBUG66: Found pool groups: %s", paste(pool_group_names, collapse=", ")))
      # Identify samples that belong to Pool groups
      samples_in_design <- rownames(design_matrix)
      pool_samples <- samples_in_design[design_matrix[[grouping_variable]] %in% pool_group_names]
      
      # Filter to samples present in both design matrix and data matrix columns
      pool_samples_in_data <- intersect(pool_samples, colnames(data_matrix))
      
      if (length(pool_samples_in_data) > 0) {
        # Log Pool/QC exclusion details
        message(sprintf("*** NEG CTRL ANOVA: Detected %d Pool/QC group(s): %s ***", 
                       length(pool_group_names), paste(pool_group_names, collapse = ", ")))
        message(sprintf("*** NEG CTRL ANOVA: Excluding %d Pool samples from ANOVA ***", 
                       length(pool_samples_in_data)))
        message(sprintf("   DEBUG66: Pool samples: %s", paste(pool_samples_in_data, collapse=", ")))
        
        # Create filtered matrices excluding Pool samples
        non_pool_samples <- setdiff(colnames(data_matrix), pool_samples_in_data)
        data_matrix_for_anova <- data_matrix[, non_pool_samples, drop = FALSE]
        design_matrix_for_anova <- design_matrix[non_pool_samples, , drop = FALSE]
        
        message(sprintf("*** NEG CTRL ANOVA: Using %d non-Pool samples for negative control selection ***", 
                       ncol(data_matrix_for_anova)))
        
        # Validate sufficient samples remain for ANOVA
        remaining_groups <- unique(design_matrix_for_anova[[grouping_variable]])
        if (length(remaining_groups) < 2) {
          stop(paste("*** NEG CTRL ANOVA ERROR: After excluding Pool samples, only", 
                    length(remaining_groups), 
                    "group(s) remain. Need at least 2 groups for ANOVA. ***"))
        }
        
        # Check samples per group
        samples_per_group <- table(design_matrix_for_anova[[grouping_variable]])
        groups_with_single_sample <- sum(samples_per_group < 2)
        if (groups_with_single_sample > 0) {
          message(sprintf("*** NEG CTRL ANOVA WARNING: %d group(s) have only 1 sample after Pool exclusion ***", 
                         groups_with_single_sample))
        }
      } else {
        message("*** NEG CTRL ANOVA: Pool groups detected but no Pool samples found in data matrix ***")
      }
    } else {
      message("*** NEG CTRL ANOVA: No Pool/QC groups detected - using all samples for ANOVA ***")
    }
  }

  ## Inspired by matANOVA function from PhosR package: http://www.bioconductor.org/packages/release/bioc/html/PhosR.html

  message("   DEBUG66: Preparing for ANOVA...")
  grps <- design_matrix_for_anova[colnames(data_matrix_for_anova), grouping_variable]
  message(sprintf("   DEBUG66: ANOVA groups vector length: %d", length(grps)))

  ps <- apply(data_matrix_for_anova, 1, function(x) {
       if( length( unique( grps[!is.na(x)] )  ) > 1 ) {
         summary(stats::aov(as.numeric(x) ~ grps))[[1]][["Pr(>F)"]][1]
       } else {
          return(NA_real_)
       }
    })

  message(sprintf("   DEBUG66: ANOVA p-values calculated. NA count: %d", sum(is.na(ps))))
  ps[is.na(ps)] <- 1

  aov <- c()

  if ( ruv_fdr_method == "qvalue") {
    message("   DEBUG66: Calculating q-values...")
    aov <- qvalue(unlist(ps))$qvalues
  } else if ( ruv_fdr_method == "BH") {
    message("   DEBUG66: Calculating BH adjusted p-values...")
    aov <- qvalue(unlist(ps), pi0=1)$qvalues
  } else {
    error( paste( "Input FDR method", ruv_fdr_method, "not valid") )
  }

  message(sprintf("   DEBUG66: q-values calculated. Range: %.4f - %.4f", min(aov, na.rm=TRUE), max(aov, na.rm=TRUE)))

  filtered_list <- aov[aov > ruv_qval_cutoff]
  message(sprintf("   DEBUG66: Proteins with q > %.4f: %d", ruv_qval_cutoff, length(filtered_list)))

  list_size <- ifelse(num_neg_ctrl > length(filtered_list), length(filtered_list), num_neg_ctrl)
  message(sprintf("   DEBUG66: Selecting top %d proteins", list_size))

  control_genes <- names(sort(filtered_list, decreasing = TRUE)[1:list_size])

  #nrow(data_matrix) - length(control_genes)
  control_genes_index <- rownames(data_matrix) %in% control_genes
  names(control_genes_index) <- rownames(data_matrix)

  message(sprintf("   DEBUG66: Final control genes selected: %d", sum(control_genes_index)))
  message("--- DEBUG66: Exiting getNegCtrlProtAnovaHelper ---")

  return(control_genes_index)

}

# ----------------------------------------------------------------------------
# extractRuvResults
# ----------------------------------------------------------------------------
## -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#'@export
extractRuvResults <- function(results_list) {

  extracted <- purrr::map(results_list, \(x){ x$results })

  names(extracted) <- names(results_list)

  return(extracted)
}

# ----------------------------------------------------------------------------
# scaleCenterAndFillMissing
# ----------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------
#' @export
#' @title Scale, Center and Fill Missing Values
#'@param input_matrix Samples are columns, rows are proteins or peptides
scaleCenterAndFillMissing <- function( input_matrix) {

  input_matrix_scaled <- scale(input_matrix, center = TRUE, scale = TRUE)


  min_data_point <- min(input_matrix_scaled, na.rm=TRUE)


  input_matrix_scaled_fill_missing <-  input_matrix_scaled
  input_matrix_scaled_fill_missing[is.na(input_matrix_scaled_fill_missing)] <- min_data_point*2

  input_matrix_scaled_fill_missing
}

# ----------------------------------------------------------------------------
# findBestNegCtrlPercentage
# ----------------------------------------------------------------------------
#' Find the Best Negative Control Percentage for RUV-III Analysis
#'
#' This function automatically determines the optimal percentage of proteins to use
#' as negative controls for RUV-III analysis by testing different percentages and
#' evaluating the separation quality between "All" and "Control" groups in canonical
#' correlation plots.
#'
#' @param normalised_protein_matrix_obj A ProteinQuantitativeData object containing
#'   the normalized protein quantification data
#' @param percentage_range A numeric vector specifying the range of percentages to test.
#'   Default is seq(1, 20, by = 1) for testing 1% to 20% in 1% increments
#' @param num_components_to_impute Number of components to use for imputation in ruvCancor.
#'   Default is 5
#' @param ruv_grouping_variable The grouping variable to use for RUV analysis.
#'   Default is "group"
#' @param ruv_qval_cutoff The FDR threshold for negative control selection.
#'   Default is 0.05
#' @param ruv_fdr_method The FDR calculation method. Default is "qvalue"
#' @param separation_metric The metric to use for evaluating separation quality.
#'   Options: "max_difference" (default), "mean_difference", "auc", "weighted_difference"
#'   Note: "weighted_difference" is deprecated.
#' @param k_penalty_weight Weight for penalizing high k values in composite score.
#'   Default is 0.5. Higher values penalize high k more strongly
#' @param max_acceptable_k Maximum acceptable k value. k values above this get heavy penalty.
#'   Default is 3
#' @param adaptive_k_penalty Whether to automatically adjust max_acceptable_k based on sample size.
#'   Default is TRUE (recommended). Set to FALSE only if you need exact reproducibility with previous results
#' @param verbose Whether to print progress messages. Default is TRUE
#'
#' @return A list containing:
#'   \itemize{
#'     \item best_percentage: The optimal percentage as a numeric value
#'     \item best_k: The optimal k value (scalar integer) for the best percentage
#'     \item best_control_genes_index: The control genes index for the best percentage
#'     \item best_separation_score: The separation score for the best percentage
#'     \item best_composite_score: The composite score (separation penalized by k value)
#'     \item optimization_results: A data frame with one row per tested percentage
#'     \item best_cancor_plot: The canonical correlation plot for the best percentage
#'     \item separation_metric_used: The separation metric that was used
#'     \item k_penalty_weight: The k penalty weight that was used
#'     \item max_acceptable_k: The maximum acceptable k value that was used
#'   }
#'
#' @importFrom logger log_info log_warn
#' @importFrom purrr imap map_dfr
#' @export
findBestNegCtrlPercentage <- function(normalised_protein_matrix_obj,
                                      percentage_range = seq(1, 20, by = 1),
                                      num_components_to_impute = 5,
                                      ruv_grouping_variable = "group",
                                      ruv_qval_cutoff = 0.05,
                                      ruv_fdr_method = "qvalue",
                                      separation_metric = "max_difference",
                                      k_penalty_weight = 0.5,
                                      max_acceptable_k = 3,
                                      adaptive_k_penalty = TRUE,
                                      verbose = TRUE) {

  # Emit weighted_difference deprecation warning once per public call
  if (identical(separation_metric, "weighted_difference")) {
    warning(
      paste0(
        "'weighted_difference' is deprecated because it up-weights high-K values ",
        "while the composite score penalizes high K. ",
        "Use 'max_difference' or 'mean_difference' instead."
      ),
      call. = FALSE
    )
  }

  message("--- DEBUG66: Entering findBestNegCtrlPercentage ---")
  message(sprintf("   DEBUG66: percentage_range: %s", paste(range(percentage_range), collapse = "-")))
  message(sprintf("   DEBUG66: adaptive_k_penalty: %s", adaptive_k_penalty))
  message(sprintf("   DEBUG66: separation_metric: %s", separation_metric))

  # Input validation
  if (!inherits(normalised_protein_matrix_obj, "ProteinQuantitativeData")) {
    stop("normalised_protein_matrix_obj must be a ProteinQuantitativeData object")
  }

  if (length(percentage_range) == 0 || any(percentage_range <= 0) || any(percentage_range > 100)) {
    stop("percentage_range must contain values between 0 and 100")
  }

  if (!separation_metric %in% c("max_difference", "mean_difference", "auc", "weighted_difference")) {
    stop("separation_metric must be one of: 'max_difference', 'mean_difference', 'auc', 'weighted_difference'")
  }

  if (k_penalty_weight < 0 || k_penalty_weight > 1) {
    stop("k_penalty_weight must be between 0 and 1")
  }

  if (max_acceptable_k < 1 || !is.numeric(max_acceptable_k)) {
    stop("max_acceptable_k must be a positive number >= 1")
  }

  if (adaptive_k_penalty && max_acceptable_k < 3) {
    stop("max_acceptable_k must be at least 3 when adaptive_k_penalty is TRUE")
  }

  # Pre-compute quantities constant across all percentages
  candidate_feature_count <- nrow(normalised_protein_matrix_obj@protein_quant_table)
  sample_size <- ncol(normalised_protein_matrix_obj@protein_quant_table) - 1L

  # Calculate adaptive max_acceptable_k if requested
  if (adaptive_k_penalty) {
    adaptive_max_k <- calculateAdaptiveMaxK(sample_size)

    if (verbose) {
      log_info("Adaptive penalty enabled: Sample size = {sample_size}, Adaptive max_acceptable_k = {adaptive_max_k} (original = {max_acceptable_k})")
    }

    max_acceptable_k <- adaptive_max_k
  }

  if (sample_size < 15 && max(percentage_range) < 30) {
    if (verbose) {
      log_warn("Small dataset detected (n={sample_size}). Consider testing higher percentages (up to 30-50%) for better negative control identification.")
      log_warn("Current range: {paste(range(percentage_range), collapse = '-')}%. May need wider range for optimal results.")
    }
  }

  if (verbose) {
    log_info("Starting optimization of negative control percentage with k value consideration...")
    log_info("Testing {length(percentage_range)} different percentages: {paste(range(percentage_range), collapse = '-')}%")
    log_info("K penalty weight: {k_penalty_weight}, Max acceptable k: {max_acceptable_k}")
    if (adaptive_k_penalty) {
      log_info("Using adaptive k penalty based on sample size")
    }
    log_info("Processing {length(percentage_range)} percentages using vectorized operations...")
  }

  # Helper: build a trace row for a failed or skipped percentage
  .make_failed_row <- function(current_percentage, status, error_reason = "",
                                realized_num_controls = NA_integer_,
                                realized_percentage = NA_real_,
                                separation_score = NA_real_,
                                best_k = NA_integer_,
                                composite_score = NA_real_,
                                control_genes_index = NULL,
                                cancor_plot = NULL) {
    list(
      percentage_requested  = current_percentage,
      candidate_feature_count = candidate_feature_count,
      realized_num_controls = realized_num_controls,
      realized_percentage   = realized_percentage,
      sample_size           = sample_size,
      best_k                = best_k,
      separation_score      = separation_score,
      composite_score       = composite_score,
      status                = status,
      error_reason          = error_reason,
      control_genes_index   = control_genes_index,
      cancor_plot           = cancor_plot
    )
  }

  # Process a single percentage, returning a fully annotated trace record
  process_percentage <- function(current_percentage, index) {
    message(sprintf("   DEBUG66 Loop: Processing percentage %d%%", current_percentage))
    if (verbose && index %% 5 == 0) {
      log_info("Testing percentage {index}/{length(percentage_range)}: {current_percentage}%")
    }

    # Step 1: Select negative controls
    ctrl_error <- NULL
    control_genes_index <- tryCatch({
      getNegCtrlProtAnova(
        normalised_protein_matrix_obj,
        ruv_grouping_variable = ruv_grouping_variable,
        percentage_as_neg_ctrl = current_percentage,
        ruv_qval_cutoff = ruv_qval_cutoff,
        ruv_fdr_method = ruv_fdr_method
      )
    }, error = function(e) {
      ctrl_error <<- e$message
      NULL
    })

    if (is.null(control_genes_index)) {
      if (verbose) {
        log_warn(paste("Percentage", current_percentage, "% : Error in getNegCtrlProtAnova:", ctrl_error))
      }
      return(.make_failed_row(current_percentage, "error_neg_ctrl_selection",
        error_reason = if (is.null(ctrl_error)) "" else ctrl_error))
    }

    # Step 2: Check minimum control count
    realized_num_controls <- sum(control_genes_index, na.rm = TRUE)
    realized_percentage <- if (candidate_feature_count > 0L) {
      100 * realized_num_controls / candidate_feature_count
    } else {
      NA_real_
    }
    message(sprintf("      DEBUG66: realized_num_controls = %d", realized_num_controls))

    if (realized_num_controls < 5L) {
      if (verbose) {
        log_warn("Percentage {current_percentage}%: Only {realized_num_controls} control genes found (minimum 5 required). Skipping.")
      }
      return(.make_failed_row(current_percentage, "skipped_insufficient_controls",
        realized_num_controls = realized_num_controls,
        realized_percentage = realized_percentage))
    }

    # Step 3: Canonical correlation
    cancor_error <- NULL
    cancorplot <- tryCatch({
      ruvCancor(
        normalised_protein_matrix_obj,
        ctrl = control_genes_index,
        num_components_to_impute = num_components_to_impute,
        ruv_grouping_variable = ruv_grouping_variable
      )
    }, error = function(e) {
      cancor_error <<- e$message
      NULL
    })

    if (is.null(cancorplot)) {
      if (verbose) {
        log_warn(paste("Percentage", current_percentage, "% : Error in ruvCancor:", cancor_error))
      }
      return(.make_failed_row(current_percentage, "error_cancor",
        realized_num_controls = realized_num_controls,
        realized_percentage = realized_percentage,
        error_reason = if (is.null(cancor_error)) "" else cancor_error,
        control_genes_index = control_genes_index))
    }

    # Step 4: Score the result
    separation_score <- calculateSeparationScore(cancorplot, separation_metric)
    message(sprintf("      DEBUG66: separation_score = %.4f",
      ifelse(is.finite(separation_score), separation_score, NaN)))

    best_k <- tryCatch(
      findBestKElbow(cancorplot),
      error = function(e) NA_integer_
    )

    if (is.na(best_k)) {
      return(.make_failed_row(current_percentage, "invalid_cancor_plot",
        realized_num_controls = realized_num_controls,
        realized_percentage = realized_percentage,
        separation_score = separation_score,
        error_reason = "findBestKElbow returned NA",
        control_genes_index = control_genes_index,
        cancor_plot = cancorplot))
    }

    best_k <- as.integer(best_k)
    composite_score <- calculateCompositeScore(
      separation_score,
      best_k,
      k_penalty_weight,
      max_acceptable_k
    )
    message(sprintf("      DEBUG66: composite_score = %.4f",
      ifelse(is.finite(composite_score), composite_score, NaN)))

    if (!is.finite(composite_score)) {
      return(.make_failed_row(current_percentage, "error_scoring",
        realized_num_controls = realized_num_controls,
        realized_percentage = realized_percentage,
        separation_score = separation_score,
        best_k = best_k,
        composite_score = composite_score,
        error_reason = "composite score is non-finite",
        control_genes_index = control_genes_index,
        cancor_plot = cancorplot))
    }

    list(
      percentage_requested  = current_percentage,
      candidate_feature_count = candidate_feature_count,
      realized_num_controls = realized_num_controls,
      realized_percentage   = realized_percentage,
      sample_size           = sample_size,
      best_k                = best_k,
      separation_score      = separation_score,
      composite_score       = composite_score,
      status                = "ok",
      error_reason          = "",
      control_genes_index   = control_genes_index,
      cancor_plot           = cancorplot
    )
  }

  all_results <- percentage_range |>
    purrr::imap(process_percentage)

  # Build optimization trace: one row per tested percentage, new schema primary,
  # deprecated aliases (percentage, num_controls, valid_plot) kept for one release cycle
  results <- all_results |>
    purrr::map_dfr(~ data.frame(
      percentage_requested    = .x$percentage_requested,
      candidate_feature_count = .x$candidate_feature_count,
      realized_num_controls   = .x$realized_num_controls,
      realized_percentage     = .x$realized_percentage,
      sample_size             = .x$sample_size,
      best_k                  = .x$best_k,
      separation_score        = .x$separation_score,
      composite_score         = .x$composite_score,
      status                  = .x$status,
      error_reason            = .x$error_reason,
      percentage              = .x$percentage_requested,
      num_controls            = .x$realized_num_controls,
      valid_plot              = identical(.x$status, "ok"),
      stringsAsFactors = FALSE
    ))

  # Deterministic winner selection — stable ordering replaces which.max()
  valid_df <- results |>
    dplyr::filter(is.finite(composite_score)) |>
    dplyr::arrange(
      dplyr::desc(composite_score),
      best_k,
      dplyr::desc(separation_score),
      percentage_requested
    )

  if (nrow(valid_df) == 0L) {
    stop("No valid percentage found. Please check your data and parameters.")
  }

  best_percentage <- valid_df$percentage_requested[[1L]]

  # Retrieve the full record (with control_genes_index and cancor_plot) for the winner
  winner_idx <- which(
    vapply(all_results, function(r) r$percentage_requested == best_percentage, logical(1L))
  )[[1L]]
  best_result <- all_results[[winner_idx]]

  best_k                <- as.integer(best_result$best_k)
  best_control_genes_index <- best_result$control_genes_index
  best_cancor_plot      <- best_result$cancor_plot
  best_separation_score <- best_result$separation_score
  best_composite_score  <- best_result$composite_score

  if (verbose) {
    log_info("Optimization complete!")
    log_info("Best percentage: {best_percentage}% (composite score: {round(best_composite_score, 4)})")
    log_info("  - Separation score: {round(best_separation_score, 4)}")
    log_info("  - Best k value: {best_k}")
    log_info("  - Number of control genes: {sum(best_control_genes_index, na.rm = TRUE)}")
  }

  message("--- DEBUG66: Exiting findBestNegCtrlPercentage ---")

  list(
    best_percentage          = best_percentage,
    best_k                   = best_k,
    best_control_genes_index = best_control_genes_index,
    best_separation_score    = best_separation_score,
    best_composite_score     = best_composite_score,
    optimization_results     = results,
    best_cancor_plot         = best_cancor_plot,
    separation_metric_used   = separation_metric,
    k_penalty_weight         = k_penalty_weight,
    max_acceptable_k         = max_acceptable_k,
    adaptive_k_penalty_used  = adaptive_k_penalty,
    sample_size              = sample_size
  )
}

