#' Legacy compatibility API
#'
#' Compatibility aliases retained from the pre-janitor package surface. New
#' code should prefer the dedicated function and class reference topics where
#' available.
#'
#' @name MultiScholaR-legacy-api
#' @aliases %||% add_node_label addColumnsToEvidenceTbl addPeptideStartAndEnd addPhosphositesPositionsString
#' @aliases addXMerStrings allPhosphositesPivotLonger allPhosphositesPivotWider averageTechReps batchQueryEvidence
#' @aliases batchQueryEvidenceGeneId buildAnnotationIdToAnnotationNameDictionary buildOneProteinToAnnotationList calcHtSize calcPeptideMatrix
#' @aliases calcPeptideMatrix,PeptideQuantitativeData-method calculateLipidCVs calculateLipidMissingness calculateLipidSumIntensityPerSample calculateMetaboliteCVs
#' @aliases calculateMissingness calculateMissingValuesPerProteinFishersTest calculatePercentMissingPerProtein calculateSumIntensityPerSample calculateTotalUniqueLipidsAcrossAssays
#' @aliases calculateTotalUniqueMetabolitesAcrossAssays chooseBestPhosphositeAccession chooseBestProteinAccession chooseBestProteinAccession,PeptideQuantitativeData-method chooseBestProteinAccessionSumDuplicates
#' @aliases cleanDesignMatrix cleanDesignMatrix,ProteinQuantitativeData-method cleanDesignMatrixCleanCategories cleanDesignMatrixCleanCategoriesMap cleanDesignMatrixCreateEachVersusAllColumns
#' @aliases cleanDesignMatrixPeptide cleanDesignMatrixPeptide,PeptideQuantitativeData-method cleanDuplicatesEnrichment clusterPathways cnetplotEdited
#' @aliases compareTwoPeptideDataObjects compareUmapComponentsPairs convertIdToAnnotation convertKeyToAttribute convertProteinAccToGeneSymbol
#' @aliases count_num_peptides count_num_proteins count_num_samples countLipidsPerSample countMetabolitesPerSample
#' @aliases countStatDaGenesHelper countUniqueLipids countUniqueMetabolites createDaResultsLongFormat createDirectoryIfNotExists
#' @aliases createDirIfNotExists createGridQC createGridQC,GridPlotData-method createIdToAttributeHash createOutputDir
#' @aliases daAnalysisWrapperFunction differentialAbundanceAnalysis differentialAbundanceAnalysis,list-method differentialAbundanceAnalysis,ProteinQuantitativeData-method differentialAbundanceAnalysisHelper
#' @aliases differentialAbundanceAnalysisHelper,LipidomicsAssayData-method differentialAbundanceAnalysisHelper,MetaboliteAssayData-method differentialAbundanceAnalysisHelper,ProteinQuantitativeData-method download_uniprot_data drawListOfFunctionalEnrichmentHeatmaps
#' @aliases drawListOfFunctionalEnrichmentHeatmapsScholar enrichedPathwayBarPlot evaluateBestMinMaxGeneSetSize extract_geneSets extractResults
#' @aliases extractRuvResults filterByScoreAndGetSimilarPeptides filterMinNumPeptidesPerProtein filterMinNumPeptidesPerProtein,ProteinQuantitativeData-method filterMinNumPeptidesPerSample
#' @aliases filterMinNumPeptidesPerSample,PeptideQuantitativeData-method filterPeptideAndExtractProbabilities filterResultsWithRevigo filterResultsWithRevigoScholar filterSamplesByLipidCorrelationThreshold
#' @aliases filterSamplesByProteinCorrelationThreshold filterSamplesByProteinCorrelationThreshold,ProteinQuantitativeData-method findBestK findBestNegCtrlPercentagePeptides findSamplesPairBelowPeptideCorrelationThreshold
#' @aliases generate_enrichment_plots generateLipidFilteringPlots generateMetaboliteFilteringPlots get_enrichplot_color get_ggrepel_segsize
#' @aliases get_param_change_message getBestPosition getBestPositionFutureMap getCategoricalColourPalette getDaResultsLongFormat
#' @aliases getDaResultsLongFormat,list-method getDaResultsWideFormat getDaResultsWideFormat,list-method getEnrichmentHeatmap getEnrichmentPlotly
#' @aliases getEnrichmentResult getEnrichmentSummary getFastaFields getFilteringProgressLipidomics getFilteringProgressMetabolomics
#' @aliases getFunctionName getFunctionNameSecondLevel getGlimmaVolcanoProteomicsWidget getInternalStandardMetrics getLipidInternalStandardMetrics
#' @aliases getLipidQuantData getLowCoefficientOfVariationProteins getMaxProb getMaxProbFutureMap getMetaboliteQuantData
#' @aliases getNegCtrlMetabAnova getNegCtrlProtAnova getNegCtrlProtAnova,ProteinQuantitativeData-method getNegCtrlProtAnovaPeptides getNegCtrlProtAnovaPeptides,PeptideQuantitativeData-method
#' @aliases getOneContinousPalette getOneRlePlotData getPcaMatrix getPcaMatrix,ProteinQuantitativeData-method getRuvIIIReplicateMatrix
#' @aliases getRuvIIIReplicateMatrix,ProteinQuantitativeData-method getUniprotAccToGeneSymbolDictionary getUniProtAnnotation getXMersList gg_save_logging
#' @aliases GridPlotData-class groupParalogPeptides InitialiseGrid InitialiseGrid,ANY-method isArgumentDefined
#' @aliases lipidIntensityFiltering list2df list2graph listifyTableByColumn log2TransformPeptideMatrix
#' @aliases logTransformAssays matchAnnotations metaboliteIntensityFiltering node_add_alpha normaliseBetweenSamples
#' @aliases normaliseUntransformedData outputDaAnalysisResults outputDaResultsAllContrasts outputDaResultsAllContrasts,ProteinQuantitativeData-method outputDeAnalysisResults
#' @aliases parseList parseNumList parseString parseType pearsonCorForSamplePairs
#' @aliases pearsonCorForSamplePairs,PeptideQuantitativeData-method peptideIntensityFiltering peptideIntensityFiltering,PeptideQuantitativeData-method peptideMissingValueImputation peptideMissingValueImputation,PeptideQuantitativeData-method
#' @aliases peptideMissingValueImputationLimpa PeptideQuantitativeData-class PeptideQuantitativeDataDiann perform_enrichment plotDensity
#' @aliases plotDensity,ggplot-method plotDensity,PeptideQuantitativeData-method plotDensity,ProteinQuantitativeData-method plotDensityList plotDensityList,ProteinQuantitativeData-method
#' @aliases plotDensityOfProteinIntensityPerSample plotEnrichmentBarplot plotHistogramOfPercentMissingPerIndvidual plotInteractiveVolcano plotInteractiveVolcano,list-method
#' @aliases plotNumSigDiffExpBarPlot plotNumSigDiffExpBarPlot,list-method plotPca plotPca,PeptideQuantitativeData-method plotPca,ProteinQuantitativeData-method
#' @aliases plotPcaBox plotPcaGgpairs plotPcaList plotPcaList,ProteinQuantitativeData-method plotPcaListHelper
#' @aliases plotPearson plotPearson,PeptideQuantitativeData-method plotPercentSamplesVsProteinQuantified plotRle plotRle,PeptideQuantitativeData-method
#' @aliases plotRle,ProteinQuantitativeData-method plotRleList plotRleList,ProteinQuantitativeData-method plotRleQc plotVolcanoS4
#' @aliases plotVolcanoS4,list-method preservePeptideNaValues preservePeptideNaValues,PeptideQuantitativeData,ProteinQuantitativeData-method preservePeptideNaValuesHelper processAndFilterData
#' @aliases processMultisiteEvidence proteinIntensityFiltering proteinIntensityFiltering,ProteinQuantitativeData-method proteinMissingValueImputationLimpa proteinTechRepCorrelation
#' @aliases proteinTechRepCorrelation,ProteinQuantitativeData-method queryRevigo readEnrichmentResultFiles removePeptidesOnlyInHek293 removePeptidesWithMissingValuesPercent
#' @aliases removePeptidesWithMissingValuesPercent,PeptideQuantitativeData-method removePeptidesWithOnlyOneReplicate removePeptidesWithOnlyOneReplicate,PeptideQuantitativeData-method removePeptidesWithoutAbundances removeProteinsWithOnlyOneReplicate
#' @aliases removeProteinsWithOnlyOneReplicate,ProteinQuantitativeData-method removeRowsWithMissingValuesPercent removeRowsWithMissingValuesPercent,ProteinQuantitativeData-method RenderReport resolveDuplicateFeatures
#' @aliases rlePcaPlotList rollUpPrecursorToPeptide rollUpPrecursorToPeptide,PeptideQuantitativeData-method runEnricher runGsea
#' @aliases runOneGoEnrichmentInOutFunction ruvCancor ruvCancor,ProteinQuantitativeData-method ruvCancorFast ruvIII_C_Varying
#' @aliases ruvIII_C_Varying,PeptideQuantitativeData-method ruvIII_C_Varying,ProteinQuantitativeData-method saveFilteredFunctionalEnrichmentTable saveListOfFunctionalEnrichmentHeatmaps saveListOfPdfs
#' @aliases savePlotDensityList savePlotPcaList savePlotRleList set_enrichplot_color setArgsDefault
#' @aliases setProteinData setProteinData,ProteinQuantitativeData-method sourceRmdFileSimple srlQvalueProteotypicPeptideClean srlQvalueProteotypicPeptideClean,PeptideQuantitativeData-method
#' @aliases summarisePeptideObject summarize_enrichment summarizeQCPlot testRequiredArguments testRequiredFiles
#' @aliases testRequiredFilesWarning umap_factor_plot uniquePhosphositesSummariseLongList uniquePhosphositesSummariseWideList update_n
#' @aliases updateFilteringProgressLipidomics updateFilteringProgressMetabolomics updateLipidFiltering updateRuvParameters writeInteractiveVolcanoPlotProteomics
#' @aliases writeInteractiveVolcanoPlotProteomicsMain writeInteractiveVolcanoPlotProteomicsWidget
#' @keywords internal
NULL
